### ISSUE TITLE
Sufia7 [CCM]: Create Collection Indexing Service Subclass

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1126]
###### Location: CollectionNorth
- [x] Confirm that solr joins actually work now. This impacts whether or not the indexing service needs to pack collection member IDs into the collection solr object.
- [x] Test performance of the stock Sufia 7, solr-join based collections
- [ ] Subclass ActiveFedora::IndexingService to index the new Community- and Collection-specific properties we're adding.
- [ ] Add a class method to export this indexing class to the Collection and Community behaviour modules  (eg. https://github.com/ualbertalib/HydraNorth/blob/master/app/models/concerns/hydranorth/collection_behavior.rb#L66)

**Estimate: 4**

**Comment by pgwillia** [comment]
```{!join from=member_ids_ssim to=id}id:bk128992v```

```
Solr parameters: {"facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword
_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "facet.query
"=>[], "facet.pivot"=>[], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=disc
over_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit
_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca 
OR read_access_person_ssim:tricia.jenkins@ualberta.ca"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"
title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.
facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.lim
it"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"
=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:bk128992v"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (137.1ms)
```

**Comment by pgwillia** [comment]
Performance does not look encouraging. Creating over 299 collections results in a 'java heap space' error in fcrepo.  Creating 100 works in 20 collections then searching or browsing is slow but usable.  Editing the works (to add files) slows to nonperformant -- browsing becomes nonperformant as well.

**Comment by pgwillia** [comment]
Here's the Java Heap Space error from fcrepo in full:
[fcrepo_heap_space_error.txt](https://github.com/ualbertalib/HydraNorth/files/400455/fcrepo_heap_space_error.txt)

**Comment by pgwillia** [comment]
Some discussion about a memory leak fix in Fedora 4.6 (now testing RC-3)

**Comment by pgwillia** [comment]
The nonperformant page is caused by a 'stack too deep' error
```
SystemStackError in CurationConcerns::GenericWorksController#show
stack level too deep
```
```
...
rsolr (1.1.1) lib/rsolr/connection.rb:15:in `execute'
rsolr (1.1.1) lib/rsolr/client.rb:181:in `execute'
rsolr (1.1.1) lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `get'
active-fedora (10.1.0) lib/active_fedora/solr_service.rb:41:in `get'
active-fedora (10.1.0) lib/active_fedora/solr_service.rb:45:in `query'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:123:in `ordered_ids'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:77:in `composite_presenter_class'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:70:in `member_presenters'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:53:in `representative_presenter'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:55:in `representative_presenter'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:55:in `representative_presenter'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:55:in `representative_presenter'
curation_concerns (1.2.0) app/presenters/curation_concerns/work_show_presenter.rb:55:in `representative_presenter'
...
curation_concerns (1.2.0) app/views/curation_concerns/base/_representative_media.html.erb:1:in `__usr_lib___ruby_gems_______gems_curation_concerns_______app_views_curation_concerns_base__representative_media_html_erb__285447302014266728_70347447031320'
```

**Comment by pgwillia** [comment]
How about that! The fcrepo-webapp 4.6.0-RC  does seem to fix my problems!

```
[root@sufia7 sufia7]# grep join log/development.log -A 1
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:0p096692m"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (74.8ms)
--
URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby&fl=id&fq=%7B%21join+from%3Dordered_targets_ssim+to%3Did%7Did%3A%22707957706%2Flist_source%22&q=%7B%21field+f%3Dhas_model_ssim%7DFileSet&qt=standard

--
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:nz805z70r"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (14.4ms)
--
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:nz805z70r"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "start"=>10, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (7.6ms)
--
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:cj82k734s"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (23.9ms)
--
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:xs55mc089"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (10.8ms)
--
Solr query: get select {"qt"=>"search", "facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "keyword_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "fq"=>["({!terms f=edit_access_group_ssim}public,registered) OR ({!terms f=discover_access_group_ssim}public,registered) OR ({!terms f=read_access_group_ssim}public,registered) OR edit_access_person_ssim:tricia.jenkins@ualberta.ca OR discover_access_person_ssim:tricia.jenkins@ualberta.ca OR read_access_person_ssim:tricia.jenkins@ualberta.ca", "{!terms f=has_model_ssim}GenericWork,Collection", "{!join from=member_ids_ssim to=id}id:8s45q882q"], "rows"=>10, "qf"=>"title_tesim name_tesim", "facet"=>true, "f.human_readable_type_sim.facet.limit"=>6, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr fetch (7.1ms)
```

**Comment by pgwillia** [comment]
how does the requirement to facet by Community impact the PCDM data model wrt Solr joins for collections/do Collections only point at items and not the other way around, and do we need to change that?

**Comment by pgwillia** [comment]
I *think* the only change that would be needed is to add facetable to the title field in the app/controllers/catalog_controller.rb configuration. It might be an extra query on the results page, but the facet can be retrieved with ```q={!join from=id to=member_ids_ssim}<your query here>``` 

i.e. 
```
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":41,
    "params":{
      "q":"{!join from=id to=member_ids_ssim}keyword_tesim:jacks_keyword",
      "facet.field":"title_tesim",
      "indent":"on",
      "rows":"0",
      "wt":"json"}},
  "response":{"numFound":204,"start":0,"maxScore":1.0,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "title_tesim":[
        "collection",204,
        "0",2,
        "1",2,
        "10",2,
        "11",2,
        "12",2,
        "13",2,
        "14",2,
        "15",2,
        "16",2,
        "17",2,
        "18",2,
        "19",2,
        "2",2,
        "3",2,
        "4",2,
        "5",2,
        "6",2,
        "7",2,
        "8",2,
        "9",2,
        "100",1,
        "101",1,
        "102",1,
        "103",1,
        "104",1,
        "105",1,
        "106",1,
        "107",1,
        "108",1,
        "109",1,
        "110",1,
        "111",1,
        "112",1,
        "113",1,
        "114",1,
        "115",1,
        "116",1,
        "117",1,
        "118",1,
        "119",1,
        "120",1,
        "121",1,
        "122",1,
        "123",1,
        "124",1,
        "125",1,
        "126",1,
        "127",1,
        "128",1,
        "129",1,
        "130",1,
        "131",1,
        "132",1,
        "133",1,
        "134",1,
        "135",1,
        "136",1,
        "137",1,
        "138",1,
        "139",1,
        "140",1,
        "141",1,
        "142",1,
        "143",1,
        "144",1,
        "145",1,
        "146",1,
        "147",1,
        "148",1,
        "149",1,
        "150",1,
        "151",1,
        "152",1,
        "153",1,
        "154",1,
        "155",1,
        "156",1,
        "157",1,
        "158",1,
        "159",1,
        "160",1,
        "161",1,
        "162",1,
        "163",1,
        "164",1,
        "165",1,
        "166",1,
        "167",1,
        "168",1,
        "169",1,
        "170",1,
        "171",1,
        "172",1,
        "173",1,
        "174",1,
        "175",1,
        "176",1,
        "177",1,
        "178",1]},
    "facet_ranges":{},
    "facet_intervals":{},
    "facet_heatmaps":{}},
  "spellcheck":{
    "suggestions":[],
    "correctlySpelled":true}}
```
The collection name doesn't appear as expected because I'm using the english text field (it's been tokenized) to facet on.  facetable should create a string field to facet title on. 

I guess one concern would be the counts? This would show a count of 1 for each collection mentioned.

**Comment by pgwillia** [comment]
Ooh! https://github.com/projecthydra/curation_concerns/pull/888/files might do the indexing service for us!

**Comment by weiweishi** [comment]
Have working code on our code base with Esme's new collection member branch. Will create a PR to his branch

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#51
