### ISSUE TITLE
Problem in 1.3.0: recent documents on front page

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1215]
1.3.0 on era-test is returning 500 errors for the home page. The problem seems to be in the recent document retrieval:

```
App 24951 stderr: 	from /var/www/sites/hydranorth/app/views/layouts/homepage.html.erb:85:in `_app_views_layouts_homepage_html_erb__3202132486772748544_70096457940660'
```

which is 

```
<%= render partial: "recent_document", collection: [@recent_documents.first], locals: {display_thumbs: true, display_access: true} %>
```

If I delete that line and restart httpd, the error doesn't happen. As far as I can tell the Solr index contains the right documents (it's a recent clone of production). [Solr query](http://solr-test.library.ualberta.ca:8080/solr/hydranorth/select?fq=has_model_ssim:GenericFile%20AND%20(edit_access_group_ssim:public%20OR%20discover_access_group_ssim:public%20OR%20read_access_group_ssim:public)&sort=system_create_dtsi%20desc&rows=4&facet=true&facet.field=resource_type_sim&facet.field=creator_sim&facet.field=subject_sim&facet.field=language_sim&facet.field=hasCollection_ssim&facet.field=year_created_sim&facet.field=publisher_sim&facet.field=contributor_sim) (with everything but the facet limits)

**Comment by pgwillia** [comment]
I'm seeing a different error in the logs than @pbinkley 

```
App 16580 stderr: [ 2016-07-13 10:07:00.9786 16665/0x000000017de488(Worker 1) utils.rb:84 ]: *** Exception ActionView::Template::Error in Rack application object (undefined method `track_generic_files_path' for 
#<#<Class:0x007f57151e4010>:0x00000009d83750>) (process 16665, thread 0x000000017de488(Worker 1)):
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/polymorphic_routes.rb:222:in `polymorphic_method'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:94:in `session_tracking_path'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:87:in `session_tracking_params'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:46:in `document_link_params'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:42:in `link_to_document'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/catalog_helper_behavior.rb:191:in `render_thumbnail_tag'
App 16580 stderr:       from /var/www/sites/hydranorth/app/views/homepage/_recent_document.html.erb:6:in `block in _app_views_homepage__recent_document_html_erb__727108345499865658_82912700'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/capture_helper.rb:38:in `capture'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/url_helper.rb:184:in `link_to'
App 16580 stderr:       from /var/www/sites/hydranorth/app/views/homepage/_recent_document.html.erb:5:in `_app_views_homepage__recent_document_html_erb__727108345499865658_82912700'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:145:in `block in render'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:333:in `instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:143:in `render'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:436:in `block in collection_with_template'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:432:in `map'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:432:in `collection_with_template'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:324:in `render_collection'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:306:in `block in render'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.2.5.2/li
App 16580 stderr: b/active_support/notifications.rb:164:in `instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/partial_renderer.rb:305:in `render'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:51:in `render_partial'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:25:in `render'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionview-4.2.5.2/lib/action_view/helpers/rendering_helper.rb:32:in `render'
App 16580 stderr:       from /var/www/sites/hydranorth/app/views/layouts/homepage.html.erb:85:in `_app_views_layouts_homepage_html_erb__3522086319940632218_70005996321720'
```

I think this might actually be related to the downloads changes...

[app/views/homepage/_recent_document.html.erb]
 ```6           <%= render_thumbnail_tag recent_document, { width: "100%" } %>```

**Comment by pgwillia** [comment]
We discovered this (and some other items with test prefix) have items in solr but not in fedora.  Our current hypothesis is this mismatch is causing this error.

**Comment by pgwillia** [comment]
```
App 16580 stderr: [ 2016-07-13 10:07:00.9786 16665/0x000000017de488(Worker 1) utils.rb:84 ]: *** Exception ActionView::Template::Error in Rack application object (undefined method `track_generic_files_path' for 
#<#<Class:0x007f57151e4010>:0x00000009d83750>) (process 16665, thread 0x000000017de488(Worker 1)):
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/polymorphic_routes.rb:222:in `polymorphic_method'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:94:in `session_tracking_path'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:87:in `session_tracking_params'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:46:in `document_link_params'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/url_helper_behavior.rb:42:in `link_to_document'
App 16580 stderr:       from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/helpers/blacklight/catalog_helper_behavior.rb:191:in `render_thumbnail_tag'
```
is the common trace but originates from different views: recent, homepage, catalog

**Comment by pbinkley** [comment]
Current status: we believe this is a problem with ghost documents in Solr, due to syncing the Fedora data from production without syncing the Solr index. We're waiting for a fresh sync of both.
