### ISSUE TITLE
sitemap generator fails

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1238]
```
rake aborted!
NoMethodError: undefined method `first' for nil:NilClass
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/file.rb:72:in `described_by'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/with_metadata/metadata_node.rb:25:in `metadata_uri'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/with_metadata/metadata_node.rb:35:in `ldp_source'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/with_metadata/metadata_node.rb:9:in `initialize'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/file.rb:131:in `new'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/file.rb:131:in `metadata'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/file/attributes.rb:18:in `digest'
/var/www/sites/hydranorth/config/sitemap.rb:17:in `block (2 levels) in <top (required)>'
/var/www/sites/hydranorth/config/sitemap.rb:9:in `each'
/var/www/sites/hydranorth/config/sitemap.rb:9:in `block in <top (required)>'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:165:in `instance_exec'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:165:in `build!'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/tasks/sitemap.rake:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => sitemap:generate
(See full trace by running task with --trace)

real    850m46.311s
user    506m3.711s
sys     281m14.219s
```

**Comment by pgwillia** [comment]
```hash: gf.characterization.digest.first.to_s, length: gf.file_size.first``` probably for item where characterization isn't completed.

**Comment by pgwillia** [comment]
Which is prefered? ```hash = gf.characterization.digest.first.to_s rescue nil``` or ```gf.characterization.digest.try(:first).try(:to_s)```

**Comment by mbarnett** [comment]
If I'm reading sitemap.rb right, do we want a nil creeping into the ```hash:``` attribute there? I'd be concerned about how the crawler would react to the string 'nil' appearing in a bunch of sitemap entries. 

Should it call ```next``` on rescue and skip the current item instead? Or should that line be refactored into multiple lines that build up the entry and can omit keys like ```hash``` where they'd contain garbage?

**Comment by weiweishi** [comment]
I'd also support @mbarnett's suggestion on call ```next``` and log the object, as we do want to tackle the ones that failed characterization.
