### ISSUE TITLE
sitemap generator fails

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1249]
On era-test still fails after ~24 hours. This time seems to be related to file operations creating the sitemap.xml and fragments.
```
rake aborted!
unknown file type: /tmp/sitemap.xml20160829-7018-kmje3j
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generato
r.rb:179:in `block in save'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `each'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `each_with_index'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `save'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/tasks/sitemap.rake:13:in `block (2 levels) in <top (required)>'
Errno::EXDEV: Invalid cross-device link @ sys_fail2 - (/tmp/sitemap.xml20160829-7018-kmje3j, /var/www/sites/hydranorth/public/sitemaps/sitemap-fragment-1.xml)
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:179:in `block in save'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `each'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `each_with_index'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/sitemap/generator.rb:177:in `save'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/rails-sitemap-b5552f24c6ab/lib/tasks/sitemap.rake:13:in `block (2 levels) in <top (required)>'
Tasks: TOP => sitemap:generate
(See full trace by running task with --trace)

real    1451m28.994s
user    920m8.568s
sys     415m30.633s
```

**Comment by pgwillia** [comment]
@henryzhang87 I think that the tmpwatch.sh cron job may have removed the file before it could be moved to /var/www/sites/hydranorth/public:

```Aug 30 12:00:01 oldham CROND[4815]: (root) CMD (find /tmp -maxdepth 1 -mmin +5 -type f ! -name 'passenger*' -exec rm -f {} \;)```

Could we add -name 'sitemap.xml*' to the rule?

**Comment by pgwillia** [comment]
@henryzhang87 thanks!  Running the generator again.

**Comment by pgwillia** [comment]
Success!
```
real	1451m28.994s
user	920m8.568s
sys	415m30.633s
```
