### ISSUE TITLE
fresh deploy of master in dev environment giving rsolr error

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1317]
```
RSolr::Error::Http - 500 Internal Server Error Error: {'responseHeader'=>{'status'=>500,'QTime'=>29},'error'=>{'msg'=>'java.io.FileNotFoundException: /var/www/sites/hydranorth/jetty/solr/development-core/data/tlog/tlog.0000000000000000000 (No such file or directory)','trace'=>'org.apache.solr.common.SolrException: java.io.FileNotFoundException: /var/www/sites/hydranorth/jetty/solr/development-core/data/tlog/tlog.0000000000000000000 (No such file or directory) at org.apache.solr.update.TransactionLog.<init>(TransactionLog.java:181) at org.apache.solr.update.TransactionLog.<init>(TransactionLog.java:139) at org.apache.solr.update.UpdateLog.ensureLog(UpdateLog.java:834) at org.apache.solr.update.UpdateLog.add(UpdateLog.java:396) at org.apache.solr.update.UpdateLog.add(UpdateLog.java:382) at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:259) at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:164) at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69) at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51) at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:926) URI: http://localhost:8983/solr/development/update?wt=ruby&softCommit=true Request Headers: {"Content-Type"=>"text/xml"} Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"system_create_dtsi\">2016-11-24T16:45:09Z</field><field name=\"system_modified_dtsi\">2016-11-24T16:45:09Z</field><field name=\"active_fedora_model_ssi\">Batch</field><field name=\"has_model_ssim\">Batch</field><field name=\"id\">f1881k888</field><field name=\"object_profile_ssm\">{\"id\":\"f1881k888\",\"creator\":[],\"title\":[],\"status\":[]}</field></doc></add>" Backtrace: /usr/lib64/ruby/gems/2.3.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response' /usr/lib64/ruby/gems/2.3.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute' /usr/lib64/ruby/gems/2.3.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive' (eval):2:in `post' /usr/lib64/ruby/gems/2.3.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in `update' /usr/lib64/ruby/gems/2.3.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:102:in `add' /usr/lib64/ruby/gems/2.3.0/gems/active-fedora-9.4.2/lib/active_fedora/solr_service.rb:130:in `add' /usr/lib64/ruby/gems/2.3.0/gems/active-fedora-9.4.2/lib/active_fedora/indexing.rb:32:in `update_index' /usr/lib64/ruby/gems/2.3.0/gems/active-fedora-9.4.2/lib/active_fedora/indexing.rb:54:in `create_record' /usr/lib64/ruby/gems/2.3.0/gems/active-fedora-9.4.2/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record' /usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
```

**Comment by pgwillia** [comment]
I removed the jetty dir and killed jetty and re-ran `rake jetty:clean` and `rake jetty:start` Seemed to fix it.
