### ISSUE TITLE
Mysql2::Error: Lost connection to MySQL server

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/HydraNorth#354]
<b>Time: </b> May 27 15:59:10 2015
<b>Host:</b>  oldham
<b>Log file:</b>  /var/log/httpd/error_log
<b>Errors messages:</b> below
<b>Comments: </b>

 we saw this kind of error messages when we were migrating users.txt. we found out in the migration script, to migrate each user, two select queries, and one save are involved. Each save
is a transaction. When this happens in a short period of time, MySQL connection lost. An explicit call to close connection to MySQL after each save resolved the problem (maybe slower, but stabler)

<b>Details of Error Messages:</b>
App 2390 stderr: DEPRECATION WARNING: Blacklight::Solr::Document::DublinCore is deprecated; use Blacklight::Document::DublinCore instead. (called from extend at /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.12.1/lib/blacklight/document/extensions.rb:27)
App 10790 stdout:

<li>[Wed May 27 15:59:07 2015] [error] [client 129.128.217.81] ModSecurity: Error reading request body: Connection reset by peer [hostname "era-test.library.ualberta.ca"] [uri "/files/x920n803h"] [unique_id "VWY@K4GA2VgAACozfxIAAABb"]
<li>[Wed May 27 15:59:10 2015] [error] [client 129.128.217.81] ModSecurity: Error reading request body: Connection reset by peer [hostname "era-test.library.ualberta.ca"] [uri "/files"] [unique_id "VWY@LoGA2VgAACpDAbcAAABh"]
<li>[Wed May 27 15:59:30 2015] [error] [client 129.128.217.81] ModSecurity: Error reading request body: Connection reset by peer [hostname "era-test.library.ualberta.ca"] [uri "/files/1g05ff21c"] [unique_id "VWY@QYGA2VgAACps2DYAAABn"]
App 2390 stderr: [ 2015-05-27 15:59:38.6669 13166/0x00000000f60d88(Worker 1) utils.rb:84 ]: *** Exception ActiveRecord::StatementInvalid in Rack application object (Mysql2::Error: Lost connection to MySQL server during query: BEGIN) (process 13166, thread 0x00000000f60d88(Worker 1)):
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:319:in `begin_db_transaction'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/transaction.rb:170:in `initialize'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/transaction.rb:52:in `new'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/transaction.rb:52:in `begin'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:231:in `begin_transaction'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:208:in `within_new_transaction'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/action_dispatch/session/active_record_store.rb:81:in `block in set_session'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/logger_silence.rb:16:in `silence'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/action_dispatch/session/active_record_store.rb:78:in `set_session'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:342:in `commit_session'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:226:in `context'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/ldp_cache.rb:26:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/static.rb:84:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
App 2390 stderr:        from /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
App 2390 stderr:        from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.58/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 2390 stderr:        from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 2390 stderr:        from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 2390 stderr:        from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by henryzhang87** [comment]
We disabled ModSecurity due to performance impact.
