### ISSUE TITLE
community uuid:1d805... does not migrate

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#581]
We get an error: 

```
[INFO  2015-09-01 20:04:16] Download the original foxml uuid:1d805a1e-b0af-49e9-8412-94e3bc026d17
[ERROR 2015-09-01 20:04:17] RDF was not parsable, ["/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:108:in `block in check_for_errors'", 
"/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `tap'", 
"/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `check_for_errors'", 
"/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:89:in `put'", 
"/usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.3.0/lib/active_fedora/caching_connection.rb:24:in `put'", 
"/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/resource.rb:72:in `create'", 
"/usr/lib64/ruby/gems/2.1.0/gems/ldp-0.3.1/lib/ldp/resource/rdf_source.rb:21:in `create'", 
"/usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.3.0/lib/active_fedora/persistence.rb:147:in `create_record'", 
"/usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.3.0/lib/active_fedora/indexing.rb:45:in `create_record'", 
"/usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.3.0/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'", 
"/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'", 
"/usr/lib64/ruby/gems/2.1.0/gems/activesupport-4.2.3/ ...
```
I don't see anything wrong in the FOXML to explain this. @anayram notes that this community has restricted access, which might explain it.

**Comment by anayram** [comment]
Looks like this file (uuid:1d805a1e-b0af-49e9-8412-94e3bc026d17) is open access but its community isn't. This foxml corresponds to the collection "University Delegate (CIHR) Information", which is associated with the *restricted* community Grant Assist Program (uuid:4eb8813a-040f-4a15-a42a-7e6345542b0c)

```xml
<isMemberOf rdf:resource="info:fedora/uuid:4eb8813a-040f-4a15-a42a-7e6345542b0c"/>
```

**Comment by anayram** [comment]
Item migrated.
