### ISSUE TITLE
Migration specs fail

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#588]
I think the test metadata may need to be updated.

```
Failures:

  1) Migration rake tasks migration:eraitem - standard item item should be migrated
     Failure/Error: expect(subject.license).to eq "Creative Commons Attribution-Non-Commercial-No Derivatives 3.0 Unported"
       
       expected: "Creative Commons Attribution-Non-Commercial-No Derivatives 3.0 Unported"
            got: "I am required to use/link to a publisher's license"
       
       (compared using ==)
     # ./spec/tasks/migration_rake_spec.rb:20:in `block (3 levels) in <top (required)>'

  2) Migration rake tasks migration:era_collection_community - community Community should be migrated
     Failure/Error: expect(subject.fedora3uuid).to eq "uuid:d04b3b74-211d-4939-9660-c390958fa2ee"
       
       expected: "uuid:d04b3b74-211d-4939-9660-c390958fa2ee"
            got: nil
       
       (compared using ==)
     # ./spec/tasks/migration_rake_spec.rb:100:in `block (3 levels) in <top (required)>'

  3) Migration rake tasks migration:era_collection_community - collection Community should be migrated
     Failure/Error: expect(subject.fedora3uuid).to eq "uuid:3f5739f8-4344-4ce5-9f85-9bda224b41d7"
       
       expected: "uuid:3f5739f8-4344-4ce5-9f85-9bda224b41d7"
            got: nil
       
       (compared using ==)
     # ./spec/tasks/migration_rake_spec.rb:115:in `block (3 levels) in <top (required)>'

Finished in 1 minute 8.11 seconds (files took 8.95 seconds to load)
6 examples, 3 failures
```

**Comment by pgwillia** [comment]
Glad it's not just me.  I had a dataverse migration spec fail as well

```
3) Migration rake tasks migration:dataverse dataverse item should be migrated
     Failure/Error: expect(subject.remote_resource).to eq "dataverse"

       expected: "dataverse"
            got: nil

       (compared using ==)
     # ./spec/tasks/dataverse_migration_rake_spec.rb:28:in `block (3 levels) in <top (required)>
```

**Comment by pbinkley** [comment]
Turns out I hadn't merged from master. With that, only one migration spec fails:

```
Failures:

  1) Migration rake tasks migration:era_collection_community - collection Community should be migrated
     Failure/Error: expect(subject.fedora3uuid).to eq "uuid:3f5739f8-4344-4ce5-9f85-9bda224b41d7"
       
       expected: "uuid:3f5739f8-4344-4ce5-9f85-9bda224b41d7"
            got: nil
       
       (compared using ==)
     # ./spec/tasks/migration_rake_spec.rb:115:in `block (3 levels) in <top (required)>'

Finished in 1 minute 1.57 seconds (files took 8.91 seconds to load)
6 examples, 1 failure
```

**Comment by pbinkley** [comment]
@pgwillia , that dataverse spec is passing for me. I hate this. I'll destroy my vm and start fresh.

**Comment by weiweishi** [comment]
dataverse spec is failing for me as well. @pgwillia, @pbinkley

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
dataverse spec fails when I ran the entire set but passed when I ran only that spec...hmm.

**Comment by weiweishi** [comment]
@anayram When you have a moment, could you please reprocess these test files with your latest transformations? https://github.com/ualbertalib/HydraNorth/tree/master/spec/fixtures/migration/test-metadata

You can send me the files via email or put them on the shared drive. Thanks!

Weiwei

**Comment by anayram** [comment]
@weiweishi I can't remember but it looks like I missed this request (or maybe I just didn't reply here). I suspect it is no longer needed given that it was related to migration; could you please confirm?

Maybe this ticket can be closed if those spec fails were solved.

**Comment by pgwillia** [comment]
tests passing
