### ISSUE TITLE
There's Something Wrong With Sonya's Account

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#799]
User.find_by(email: 'sonya.betz@ualberta.ca')

When she tries to visit her dashboard the application 500s, producing the following backtrace:

```
ActiveFedora::ActiveFedoraError (Model mismatch. Expected GenericFile. Got: Batch):
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:202:in `class_to_load'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:192:in `load_from_fedora'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:178:in `find_one'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:243:in `find_with_ids'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:59:in `find'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/finder_methods.rb:93:in `exists?'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/querying.rb:3:in `exists?'
  vendor/ruby/2.1.0/gems/sufia-models-6.2.0/app/models/proxy_deposit_request.rb:76:in `deleted_file?'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:132:in `reject'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:132:in `public_send'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:132:in `method_missing'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:99:in `method_missing'
  vendor/ruby/2.1.0/gems/sufia-6.2.0/app/controllers/concerns/sufia/dashboard_controller_behavior.rb:37:in `gather_dashboard_information'
  vendor/ruby/2.1.0/gems/sufia-6.2.0/app/controllers/concerns/sufia/dashboard_controller_behavior.rb:15:in `index'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
  vendor/ruby/2.1.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  vendor/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  vendor/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  vendor/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  vendor/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
  vendor/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/ruby/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/ldp_cache.rb:26:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
  vendor/ruby/2.1.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
  vendor/ruby/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
  passenger (4.0.58) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.58) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.58) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.58) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by sfbetz** [comment]
Feel free to delete me to fix this...

**Comment by pbinkley** [comment]
I wonder if an item of yours from old ERA was mismigrated. We should be able to work it out.

**Comment by sfbetz** [comment]
I only created this account as a test account, so none of my content needs to be migrated. It's all test files that should be deleted anyhow!

**Comment by pbinkley** [comment]
I believe this was resolved by deleting and recreating the account. Feel free to reopen if this still needs attention.

**Comment by sfbetz** [comment]
Sadly not resolved yet :(

On Fri, Jan 8, 2016 at 1:50 PM, Peter Binkley <notifications@github.com>
wrote:

> I believe this was resolved by deleting and recreating the account. Feel
> free to reopen if this still needs attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/799#issuecomment-170120283>
> .
>



-- 
Sonya Betz
Digital Initiatives Projects Librarian
Acting Digital Repository Services Librarian



*University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
*780-492-1718*

**Comment by mbarnett** [comment]
Sonya, is this bug still valid?

**Comment by sfbetz** [comment]
It sure is. Easiest solution is probably to delete my account completely and I can recreate it myself.

**Comment by mbarnett** [comment]
@weiweishi or @pbinkley or someone else with Production access, if you delete Sonya's personal account from the rails console, we can close this out.

**Comment by weiweishi** [comment]
I've deleted the user. @sfbetz could you try again with a new registration?

**Comment by sfbetz** [comment]
Success!! Closing.
